#include "rgss_export.h" // Generated by CMake to export symbols in DLL.

extern "C" {

// Prototype entry point for Ruby.
void Init_rgss ();

}

// Exposed entry point for RGSS.
void RGSS_EXPORT startRGSS ()
{
    Init_rgss();
}
