// Ruby script to C code conversion utility.
// Generates a C file with a string containing raw data from the contents of a Ruby script.
// Original code found here: http://stackoverflow.com/a/11814544
// Code modified from the original.

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

FILE* tryOpen (const char *path, const char *mode)
{
    FILE* f = fopen(path, mode);
    if(f == NULL)
    {
        perror(path);
        exit(EXIT_FAILURE);
    }
    return f;
}

void printUsage (char *progName)
{
    fprintf(stderr, "Usage: %s <INPUT> <OUTPUT> <SYMBOL>\n"
                    "  Creates <OUTPUT> file from the contents of <INPUT>\n"
                    "  A char array named <SYMBOL> will be defined in <OUTPUT>\n",
            progName);
    exit(EXIT_FAILURE);
}

void printHexContents (FILE *inFile, FILE *outFile)
{
    unsigned char buffer[1024];
    int bytes   = 0; // Number of bytes read.
    int linePos = 0; // Number of hex values printed to the current line.

    // Continue looping until the end of the file is reached.
    do
    {
        // Read up until the buffer is full.
        bytes = fread(buffer, 1, sizeof(buffer), inFile);

        // Print the hex format of each byte.
        int i;
        for(i = 0; i < bytes; i++)
        {
            fprintf(outFile, "0x%02x, ", buffer[i]);

            // Start a new line every 16 hex values.
            if(++linePos >= 16)
            {
                fprintf(outFile, "\n");
                linePos = 0;
            }
        }
    } while(bytes > 0);
}

void generateOutputFile (const char *inFileName, const char *outFileName, const char *symbol)
{
    // Try to open the input and output files.
    FILE *inFile  = tryOpen(inFileName, "r");
    FILE *outFile = tryOpen(outFileName, "w");

    // Print initial declaration.
    fprintf(outFile, "/* Auto-generated by rb2c\n"
                     "   Contents generated from: %s */\n", inFileName);
    fprintf(outFile, "#include <stdlib.h>\n");
    fprintf(outFile, "const char %s[] = {\n", symbol);

    // Print the hex contents of the input file.
    printHexContents(inFile, outFile);

    // Print closing to declaration.
    fprintf(outFile, "0x00 };\n"); // Make sure to put a NULL-terminator at the end.
    fprintf(outFile, "const size_t %s_len = sizeof(%s);\n", symbol, symbol);

    // Close the files.
    fclose(inFile);
    fclose(outFile);
}

int main (int argc, char **argv)
{
    // Check arguments.
    if(argc < 4)
        printUsage(argv[0]);

    // Get arguments and the output filename.
    const char *rubyFileName = argv[1];
    const char *cFileName    = argv[2];
    const char *symbol       = argv[3];

    generateOutputFile(rubyFileName, cFileName, symbol);

    return EXIT_SUCCESS;
}
